### ISSUE TITLE
byte-opt.el commentary attribution

### ISSUE THREAD

**Issue by dmringo** [rocky/elisp-lap#70]
I think the [attribution for the quote](https://github.com/rocky/elisp-bytecode/blob/026e0c9a8c3328994c69616d35ae7a955d9a3f64/intro.texi#L79) found lisp/emacs-lisp/byte-opt.el to Eric Naggum isn't correct.  The bit about racehorses and pigs is from [East of Eden](https://www.goodreads.com/quotes/7745830-you-can-t-make-a-race-horse-of-a-pig-no) but more significantly, I think Jamie Zawinski may be the one who added it and [the bit about turbocharged VW bugs](https://github.com/emacs-mirror/emacs/blob/5130a95cd187bb67aea7252edb334a470bc3cf79/lisp/emacs-lisp/byte-opt.el#L32-L35) below it (in Lucid Emacs, presumably) since it's present in [the initial checkin of the file by Jim Blandy](https://github.com/emacs-mirror/emacs/commit/1c393159a24ae0c5891c7f6367db53459f76d2e0#diff-925819e48dce264872f947e19ae7e01e) circa Emacs 18/19.

**Comment by rocky** [comment]
Ok. Points taken. Would you please revise the commentary with the links you cite? 

I don't know this stuff, and even if I did, I (would) make _lots_ of mistakes. So thanks for finding, reporting, and hopefully fixing.

**Comment by dmringo** [comment]
Sure thing.  I don't know much about this either -- I just saw the attribution and went down an Emacs history rabbit-hole that happened to reveal that Eric was probably not the original author.

**Comment by rocky** [comment]
@dmringo See if 91e303e addresses your observations. If not feel free to amend.

**Comment by dmringo** [comment]
Thanks.  Just made #71 to reflect some new info.

**Comment by rocky** [comment]
Merged, so let's close this. BTW I also spelled [Erik Naggum](https://en.wikiquote.org/wiki/Erik_Naggum)'s name incorrectly.
