### ISSUE TITLE
switch instruction doesn't jump to an offset

### ISSUE THREAD

**Issue by jsjolen** [rocky/elisp-lap#74]
Hi,

```
switch-like jump table.  Top of stack is a variable reference.  Below that is ahash table mapping compared values to instructions offsets.
```
The hash table values aren't offsets, they're pc values.

So it's not:

```
pc = pc + ht.lookup(TOS);
```

It's:

```
pc = ht.lookup(TOS);
```

This is seen in `bytecode.c`:

```
	op_branch:
	  op -= pc - bytestr_data;
	op_relative_branch:
	  pc += op;
	  NEXT;
```

Inlining the computation we get `pc = pc + op - pc - byte_strdata == op - byte_strdata`.

**Comment by rocky** [comment]
Thanks for the correction. See if  486d128 addresses this.

**Comment by jsjolen** [comment]
LGTM!

**Comment by rocky** [comment]
Great! Let's close this then. 

I am sure there are other bugs if not omissions, especially  in the control-flow portion of that doc. We haven't had anyone other than me going over the doc with any regulartity.

So if you find more problems let me know and we can fix this.  

Thanks!
