### ISSUE TITLE
`call` opcode documentation incorrect?

### ISSUE THREAD

**Issue by blahgeek** [rocky/elisp-lap#79]
In the document:

> 1 byte for call[0] .. call[4]; 2 bytes for call[5], 8-bit operand; 3 bytes for call[6], 16-bit operand.

Apparently `call[0]` to `call[5]` should be 1 byte, `call[6]` is 2 bytes and `call[7]` is 3 byte

**Comment by rocky** [comment]
This should be corrected now.  If something is still wrong, let me know or I think you can reopen this issue.

Thanks for the correction.
